### ISSUE TITLE
It's "Yom Tov" not "Yontef"

### ISSUE THREAD

**Issue by ix4** [Noleli/isyontefearlythisyear#1]
First of all I love this project, great work.
But the word is [Yom Tov](https://en.m.wikipedia.org/wiki/Yom_Tov) (Hebrew: יום טוב, literally *good day*) not *Yontef*.
FYI in modern Israeli Hebrew the word *Chag* (Hebrew: חג, meaning *holiday*) is used.

**Comment by Noleli** [comment]
Thanks! I do know all that. Just one in a long line of Ashkenazi bastardizations of לשון הקודש. The way I grew up, we said things like *keynahora* for קיין עין הרע and *shaleshudis* for סעודה שלישית. *Yontef* for יום טוב was right there with these.

I was honestly pretty surprised (and amused) by how much pushback and confusion there was over this editorial decision. Reddit had a [nice long discussion](https://www.reddit.com/r/Judaism/comments/a1hfyd/comment/eapz07h) about it.

If my great-grandmother could spell the English word “hat” as עט in Yiddish, I can spell יום טוב as Yontef. Wontfix :)

**Comment by ix4** [comment]
lol I respect that. I myself am Ashkenazi & a fluent Yiddish speaker constantly tasked with "Askenazi to Hebrew" translation between my GF who's "Jewish" lexicon is exclusively "Ashkenazi bastardized words" and my Israeli friends

**Comment by Noleli** [comment]
Someone’s gotta do it!

**Comment by Noleli** [comment]
Alright, the internet complained loudly enough. isyomtovearlythisyear.com and isyomtovlatethisyear.com now also work.
